export { type Dictionary, type PropertyType, type OnlyValues } from './CommonTypes';
export { castToConstantable, instanceOfConstantable, type IConstantable } from './Constantable';
export { castToEditable, instanceOfEditable, type IEditable } from './Editable';
export { castToEntity, instanceOfEntity, type IEntity } from './Entity';
export { castToGrouping, instanceOfGrouping, type IGrouping } from './Grouping';
export { type TGuid } from './Guid';
export { type IHasRequiredOwner } from './HasOwner';
export { castToIdentifierId, instanceOfIdentifierId, type IIdentifierId } from './IdentifierId';
export { type TKey } from './Key';
export { type MaybeNull, type MaybeUndef } from './MaybeTypes';
export { castToNameable, instanceOfNameable, type INameable } from './Nameable';
export { type IPoint } from './Point';
export { type IProxiedObject } from './ProxiedObject';
export { type IRect } from './Rect';
export { type IRectOffset, type IRectSizeOffset } from './RectOffset';
export { castToResult, instanceOfResult, type IResult, type IResultMessage } from './Result';
export { type ISize } from './Size';
export { type IStorage } from './Storage';
