export { castToChangeStateNotifier, instanceOfChangeStateNotifier, type IChangeStateNotifier } from './ChangeStateNotifier';
export { type Dictionary, type MakeOptional, type OnlyValues, type PropertyType, type ReplaceValues } from './CommonTypes';
export { castToConstantable, instanceOfConstantable, type IConstantable } from './Constantable';
export { castToDatasavable, instanceOfDatasavable, type IDatasavable } from './Datasavable';
export { castToDestroyable, instanceOfDestroyable, type IDestroyable } from './Destroyable';
export { castToDisplayNameable, instanceOfDisplayNameable, type IDisplayNameable } from './DisplayNameable';
export { castToEditable, instanceOfEditable, type IEditable } from './Editable';
export { castToEntity, instanceOfEntity, type IEntity } from './Entity';
export { castToEquatable, instanceOfEquatable, type IEquatable } from './Equatable';
export { castToGrouping, instanceOfGrouping, type IGrouping } from './Grouping';
export { type TGuid } from './Guid';
export { castToHasRequiredOwner, instanceOfHasRequiredOwner, type IHasRequiredOwner } from './HasOwner';
export { castToIdentifierId, instanceOfIdentifierId, type IIdentifierId } from './IdentifierId';
export { type TKey } from './Key';
export { type MaybeNull, type MaybeUndef } from './MaybeTypes';
export { castToNameable, instanceOfNameable, type INameable } from './Nameable';
export { type IPoint } from './Point';
export { type IProxiedObject } from './ProxiedObject';
export { type IRecordObject } from './RecordObject';
export { type IRect } from './Rect';
export { type IRectOffset, type IRectSizeOffset } from './RectOffset';
export { castToResult, createResultFromError, instanceOfResult, type IResult, type IResultMessage } from './Result';
export { type ISize } from './Size';
export { type IStorage } from './Storage';
