import { OptionsStory } from './OptionsStory';
import { IPerson } from './PersonInfo';

export const Persons: IPerson[] = [
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png',
    id: '1',
    name: 'Даниил',
    surname: 'Дементьев',
    roleId: 1,
    tagsIds: [1],
    birthday: '1980-04-14',
    age: 44, // 2024 - 1980
    power: 87,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-8.png',
    id: '2',
    name: 'Иван',
    surname: 'Иванов',
    roleId: 2,
    tagsIds: [2, 3],
    birthday: '1980-04-14',
    age: 44,
    power: 65,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png',
    id: '3',
    name: 'Сергей',
    surname: 'Тухляк',
    roleId: 3,
    tagsIds: [1, 4],
    birthday: '1980-04-14',
    age: 44,
    power: 92,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png',
    id: '4',
    name: 'Сергей',
    surname: 'Тухляк',
    roleId: 3,
    tagsIds: [1, 4],
    birthday: '1980-04-14',
    age: 44,
    power: 78,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png',
    id: '5',
    name: 'Александр',
    surname: 'Петров',
    roleId: 4,
    tagsIds: [3],
    birthday: '1985-07-15',
    age: 39,
    power: 45,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png',
    id: '6',
    name: 'Мария',
    surname: 'Сидорова',
    roleId: 5,
    tagsIds: [2, 5],
    birthday: '1990-11-23',
    age: 34,
    power: 73,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png',
    id: '7',
    name: 'Ольга',
    surname: 'Кузнецова',
    roleId: 1,
    tagsIds: [1, 3],
    birthday: '1982-03-18',
    age: 42,
    power: 56,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png',
    id: '8',
    name: 'Дмитрий',
    surname: 'Васильев',
    roleId: 2,
    tagsIds: [4],
    birthday: '1978-09-30',
    age: 46,
    power: 88,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-9.png',
    id: '9',
    name: 'Екатерина',
    surname: 'Михайлова',
    roleId: 3,
    tagsIds: [2, 3, 5],
    birthday: '1992-05-12',
    age: 32,
    power: 67,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-10.png',
    id: '10',
    name: 'Анна',
    surname: 'Федорова',
    roleId: 4,
    tagsIds: [1, 4, 5],
    birthday: '1987-08-25',
    age: 37,
    power: 94,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png',
    id: '11',
    name: 'Михаил',
    surname: 'Николаев',
    roleId: 5,
    tagsIds: [3, 4],
    birthday: '1983-12-05',
    age: 41,
    power: 82,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png',
    id: '12',
    name: 'Наталья',
    surname: 'Павлова',
    roleId: 1,
    tagsIds: [2],
    birthday: '1991-02-14',
    age: 33,
    power: 71,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png',
    id: '13',
    name: 'Алексей',
    surname: 'Семенов',
    roleId: 2,
    tagsIds: [1, 5],
    birthday: '1975-06-28',
    age: 49,
    power: 59,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png',
    id: '14',
    name: 'Татьяна',
    surname: 'Григорьева',
    roleId: 3,
    tagsIds: [3, 4, 5],
    birthday: '1988-10-17',
    age: 36,
    power: 96,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png',
    id: '15',
    name: 'Павел',
    surname: 'Волков',
    roleId: 4,
    tagsIds: [2, 3],
    birthday: '1984-01-09',
    age: 40,
    power: 63,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png',
    id: '16',
    name: 'Юлия',
    surname: 'Захарова',
    roleId: 5,
    tagsIds: [1, 2, 4],
    birthday: '1993-04-22',
    age: 31,
    power: 77,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png',
    id: '17',
    name: 'Владимир',
    surname: 'Борисов',
    roleId: 1,
    tagsIds: [5],
    birthday: '1979-07-03',
    age: 45,
    power: 85,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-8.png',
    id: '18',
    name: 'Елена',
    surname: 'Киселева',
    roleId: 2,
    tagsIds: [2, 3, 4],
    birthday: '1986-11-11',
    age: 38,
    power: 52,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-9.png',
    id: '19',
    name: 'Артем',
    surname: 'Макаров',
    roleId: 3,
    tagsIds: [1, 3, 5],
    birthday: '1990-03-26',
    age: 34,
    power: 89,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png',
    id: '20',
    name: 'Светлана',
    surname: 'Андреева',
    roleId: 4,
    tagsIds: [4],
    birthday: '1981-09-08',
    age: 43,
    power: 68,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png',
    id: '21',
    name: 'Игорь',
    surname: 'Тихонов',
    roleId: 5,
    tagsIds: [1, 2],
    birthday: '1976-05-19',
    age: 48,
    power: 91,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png',
    id: '22',
    name: 'Валентина',
    surname: 'Соловьева',
    roleId: 1,
    tagsIds: [3, 4, 5],
    birthday: '1989-12-01',
    age: 35,
    power: 74,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png',
    id: '23',
    name: 'Константин',
    surname: 'Виноградов',
    roleId: 2,
    tagsIds: [2, 5],
    birthday: '1983-02-15',
    age: 41,
    power: 61,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png',
    id: '24',
    name: 'Лариса',
    surname: 'Романова',
    roleId: 3,
    tagsIds: [1, 4],
    birthday: '1994-06-30',
    age: 30,
    power: 79,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png',
    id: '25',
    name: 'Григорий',
    surname: 'Орлов',
    roleId: 4,
    tagsIds: [3],
    birthday: '1977-08-12',
    age: 47,
    power: 83,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png',
    id: '26',
    name: 'Алиса',
    surname: 'Ковалева',
    roleId: 5,
    tagsIds: [2, 3, 4],
    birthday: '1991-10-24',
    age: 33,
    power: 55,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png',
    id: '27',
    name: 'Роман',
    surname: 'Белов',
    roleId: 1,
    tagsIds: [1, 5],
    birthday: '1985-01-17',
    age: 39,
    power: 98,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-8.png',
    id: '28',
    name: 'Вера',
    surname: 'Медведева',
    roleId: 2,
    tagsIds: [4],
    birthday: '1992-07-08',
    age: 32,
    power: 64,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-9.png',
    id: '29',
    name: 'Станислав',
    surname: 'Абрамов',
    roleId: 3,
    tagsIds: [2, 3],
    birthday: '1979-03-21',
    age: 45,
    power: 76,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png',
    id: '30',
    name: 'Зоя',
    surname: 'Фролова',
    roleId: 4,
    tagsIds: [1, 2, 5],
    birthday: '1988-05-04',
    age: 36,
    power: 90,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png',
    id: '31',
    name: 'Виктор',
    surname: 'Лебедев',
    roleId: 5,
    tagsIds: [3, 4, 5],
    birthday: '1982-11-29',
    age: 42,
    power: 57,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png',
    id: '32',
    name: 'Ксения',
    surname: 'Егорова',
    roleId: 1,
    tagsIds: [2],
    birthday: '1995-09-13',
    age: 29,
    power: 81,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png',
    id: '33',
    name: 'Георгий',
    surname: 'Степанов',
    roleId: 2,
    tagsIds: [1, 3, 4],
    birthday: '1974-12-07',
    age: 50,
    power: 69,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png',
    id: '34',
    name: 'Маргарита',
    surname: 'Давыдова',
    roleId: 3,
    tagsIds: [5],
    birthday: '1987-02-28',
    age: 37,
    power: 93,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png',
    id: '35',
    name: 'Федор',
    surname: 'Жуков',
    roleId: 4,
    tagsIds: [2, 4],
    birthday: '1980-06-19',
    age: 44,
    power: 72,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png',
    id: '36',
    name: 'Элина',
    surname: 'Савельева',
    roleId: 5,
    tagsIds: [1, 3],
    birthday: '1993-08-02',
    age: 31,
    power: 86,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png',
    id: '37',
    name: 'Борис',
    surname: 'Рыбаков',
    roleId: 1,
    tagsIds: [4, 5],
    birthday: '1978-04-25',
    age: 46,
    power: 62,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-8.png',
    id: '38',
    name: 'Лидия',
    surname: 'Комарова',
    roleId: 2,
    tagsIds: [3],
    birthday: '1989-10-10',
    age: 35,
    power: 95,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-9.png',
    id: '39',
    name: 'Василий',
    surname: 'Крылов',
    roleId: 3,
    tagsIds: [1, 2, 5],
    birthday: '1984-07-03',
    age: 40,
    power: 58,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-10.png',
    id: '40',
    name: 'Раиса',
    surname: 'Терентьева',
    roleId: 4,
    tagsIds: [2, 3, 4],
    birthday: '1990-12-16',
    age: 34,
    power: 84,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png',
    id: '41',
    name: 'Семен',
    surname: 'Антонов',
    roleId: 5,
    tagsIds: [1, 4, 5],
    birthday: '1981-03-09',
    age: 43,
    power: 70,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png',
    id: '42',
    name: 'Евгения',
    surname: 'Ильина',
    roleId: 1,
    tagsIds: [3],
    birthday: '1994-05-22',
    age: 30,
    power: 99,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png',
    id: '43',
    name: 'Никита',
    surname: 'Сорокин',
    roleId: 2,
    tagsIds: [2, 4, 5],
    birthday: '1977-09-05',
    age: 47,
    power: 53,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png',
    id: '44',
    name: 'Диана',
    surname: 'Филиппова',
    roleId: 3,
    tagsIds: [1, 3],
    birthday: '1986-01-28',
    age: 38,
    power: 75,
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png',
    id: '45',
    name: 'Олег',
    surname: 'Марков',
    roleId: 4,
    tagsIds: [2, 5],
    birthday: '1983-11-11',
    age: 41,
    power: 100, // Максимальная сила
  },
  {
    avatar: 'https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png',
    id: '46',
    name: 'Людмила',
    surname: 'Ширяева',
    roleId: 5,
    tagsIds: [3, 4],
    birthday: '1992-08-14',
    age: 32,
    power: 66,
  },
];