export { type IGeneralBackgroundProperties } from './GeneralBackgroundProperties'
export { hasBorderProperties, hasBorderProps, type IGeneralBorderProperties } from './GeneralBorderProperties'
export { type IGeneralBaseElementProperties, type IGeneralElementProperties } from './GeneralElementProperties'
export { type IGeneralIconProperties } from './GeneralIconProperties'
export { type IGeneralTextProperties } from './GeneralTextProperties'
